<h2>Cart promo codes:</h2>
<?PHP 
//----------------debug---------------------
// echo '<pre>';
// echo 'Debug Info:<br />module name:';
// print_r($block->getData()['module_name']);
// echo '<br />type:';
// print_r($block->getData()['type']);
// echo '<br />';
// //var_dump(get_class_methods($block->getPostCollection()));
// print_r($block->getPostCollection()->getData());
// echo '</pre>';
//---------------end debug-------------------
?>


<style>
table {  font-family: arial, sans-serif;  border-collapse: collapse;  width: 100%;  margin-top: 30px;}
td, th {  border: 1px solid #dddddd;  text-align: left;  padding: 8px;  }
tr:nth-child(even) { background-color: #dddddd; }
.post-id{width:2%} .post-name{width:30%}

</style>

<table>
  <tr>
    <th class="post-id">Id</th>
    <th class="post-name">Name</th>
    <th>Times Used</th>
    <th>usage_limit</th>
    <th>ExpirationDate</th>
  </tr>
    <?php
        foreach ($block->getPostCollection() as $key=>$post){
            echo '<tr>
                    <td>'.$post->getData()['coupon_id'].'</td>
                    <td>'.$post->getData()['code'].'</td>
                    <td>'.$post->getData()['times_used'].'</td>
                    <td>'.$post->getData()['usage_limit'].'</td>
                    <td>'.$post->getData()['expiration_date'].'</td>
                  </tr>';
        }
    ?>
</table>

</body>
</html>

