<div class="my_class" 
style="background:RGBA(0,0,0,.1);
border-radius:4px;
box-shadow:1px 2px 4px #000;
text-align:center;
padding:5px 15px;
margin:0;
">
<h2>Welcome to Learn Module</h2>
<p>Hello!</p>
<p>This is experemental test module!</p>
<b><a href="http://www.youtube.com/?gl=US" target="_blank">youtube US</a></b>|
<b><a href="http://www.youtube.com/?gl=UA" target="_blank">youtube UA</a></b>|
<b><a href="http://www.youtube.com/?gl=PL" target="_blank">youtube PL</a></b>|
<b><a href="http://www.youtube.com/?gl=JP" target="_blank">youtube JP</a></b>|
<b><a href="http://www.youtube.com/?gl=RU" target="_blank">youtube RU</a></b><br />
<b><a href="http://www.yahoo.com/" target="_blank">yahoo</a></b>|
<b><a href="https://www.mageplaza.com/magento-2-module-development/create-admin-menu-magento-2.html" target="_blank">admin menu development (mageplaza.com)</a></b>|
</div>